---
- name: Ansible create transit
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  ignore_errors: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    default_container_image: centos:7
    
  tasks:
    # Pull image specified by variable default_image from the Docker Hub
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ t2_name }}"
        image: "{{ default_container_image }}"
        state: started
        privileged: yes
        command: sleep infinity
      register: result

    - name: Create symbolic link to network namespace
      file:
        src: "/proc/{{ result.container['State']['Pid'] }}/ns/net" 
        dest: "/var/run/netns/{{ t2_name }}"
        state: link 

    - name: Add transit to management network
      docker_network:
        name: "{{ mns }}"
        connected:
          - "{{ t2_name }}"
        appends: yes

    - name: Create veth pair with hypervisor
      shell: "{{ lookup('template', 'scripts/t_h_connect.j2') }}"
      args:
        executable: /bin/bash
      become: yes

    - name: Wait for containers to be started
      pause:
        seconds: 30
