---
- name: Connect container to L3 bridge
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Create veth pair between customer pc and leaf
      command: "ip link add {{ ve_l_pc }} type veth peer name {{ ve_pc_l }}"

    - name: Add veth endpoint to leaf
      command: "ip link set {{ ve_l_pc }} netns {{ l_name }}"

    - name: Up the veth end at the leaf
      command: "ip netns exec {{l_name}} ip link set {{ ve_l_pc }} up"

    - name: Link vethe endpointw to internal bridge in leaf
      command: "ip netns exec {{l_name}} brctl addif {{ l_br_name }} {{ ve_l_pc }}"

    - name: Add veth endpoint to client container
      command: "ip link set {{ ve_pc_l }} netns {{ c_name }}"

    - name: Up endpoint in the client container
      command: "ip netns exec {{ c_name }} ip link set {{ ve_pc_l }} up"

    - name: Run dhclient on client container
      command: "ip netns exec {{c_name}} dhclient {{ ve_pc_l }}"

      #    - name: Remove default route
      #command: "ip netns exec {{c_name}} ip route del default"

      # - name: Add new default route to bridge network
      #command: "ip netns exec {{c_name}} ip route add default via {{ l_br_ip }}"
