---
- name: Ansible attach leaf to spine
  hosts: "{{ hypervisors }}"
  user: root
    
  tasks:
  - name: Create bridge and network between leaf and spine
      script: "scripts/create_net.sh {{ l_s_net }} {{ l_s_br }}"
      become: yes

    - name: Attach interface to spine VMs
      command: "virsh attach-interface --domain {{ s_name }} --type network {{ l_s_net }} --model virtio"
      become: yes

    - name: Connect bridge to leaf namespace
      script: "scripts/create_veth_ns_br.sh {{ l_name }}  {{ l_ip }} {{ l_s_br }} {{ ve_l_br }} {{ ve_br_l }}"
      become: yes

    - name: Fetch spine VM IPs
      script: "scripts/getIP.py {{ s_name }}"
      args:
        executable: python
      register: spine_ips

    - debug:
        msg: "{{item.stdout}}"
      loop: "{{spine_ips.results}}"

    - name: Add Spines to host
      add_host:
        hostname: "{{item.stdout}}"
        ansible_ssh_pass: yashrocks
        groups:
          - "{{hypervisor}}_hosts"
      loop: "{{spine_ips.results}}"

- name: Ansible playbook to assign ip to spine
  hosts: ["{{hypervisor}}_hosts"]
  user: root

  tasks:
    - set_fact:
        my_idx: "{{ play_hosts.index(inventory_hostname) | int }}"
    - name: Assign IPs to spine VMs
      script: "last_dev.sh {{spine[play_hosts.index(inventory_hostname)].leaf[0].ip}}/{{spine[play_hosts.index(inventory_hostname)].ip_mask}} {{leaf[0].ad_subnet}} {{leaf[0].spine[play_hosts.index(inventory_hostname)].ip}}"