---
- name: Ansible create leaf
  hosts: "{{ hypervisors }}"
  user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    default_container_image: centos:7

  tasks:
    # Pull image specified by variable default_image from the Docker Hub
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ l_name }}"
        image: "{{ default_container_image }}"
        state: started
        privileged: yes
        command: sleep infinity
      register: result

    - name: Create symbolic link to network namespace
      file:
        src: "/proc/{{ result.container['State']['Pid'] }}/ns/net" 
        dest: "/var/run/netns/{{ l_name }}"
        state: link 
    
    - name: Create a network and bridge between leaf namespace and customer VMs
      script: "../scripts/create_net.sh {{ subnet_net }} {{ subnet_br }}"
    
    - name: Connect bridge to leaf namespace
      script: "../scripts/create_veth_ns_br.sh {{ l_name }} {{ l_ip }} {{ subnet_br }} {{ ve_l_br }} {{ ve_br_l }}"