---
- name: Ansible create leaf
  hosts: "{{ hypervisors }}"
  user: root
  become: yes
    
  tasks:
    - name: Create leaf namespace
      command: "ip netns add {{ l_name }}"
    
    - name: Create a network and bridge between leaf namespace and customer VMs
      script: "../scripts/create_net.sh {{ subnet_net }} {{ subnet_br }}"
    
    - name: Connect bridge to leaf namespace
      script: "../scripts/create_veth_ns_br.sh {{ l_name }} {{ l_ip }} {{ subnet_br }} {{ ve_l_br }} {{ ve_br_l }}"