[local]
localhost ansible_connection=local

[hypervisors]
172.16.2.1 ansible_connection=ssh ansible_ssh_user=ece792 ansible_ssh_private_key_file=keys/id_test
172.16.2.2 ansible_connection=ssh ansible_ssh_user=ece792 ansible_ssh_private_key_file=keys/id_test

[hv1_hosts]
[hv2_hosts]
