base_name: c1v2h1
cid: c1
vpc_id: v2
hypervisor: h1
subnets:
  - id: sub1
    network_id: 1
    subnet_base: 150.0.0.0
    subnet_mask: 24
    ns_ip: 150.0.0.1
    range: 150.0.0.2,150.0.0.254
    vm_ids: [1,2]
