---
- name: Ansible create VPC
  hosts: [hypervisors]
  user: root
  vars_files:
    - vars/setup.yml
    
  tasks:
    - name: Create spines
      command: "virt-clone --original routingVM -n {{cid}}_t{{ item }} --auto-clone"
      become: yes    
      with_sequence: "count={{transit_count}}"
      ignore_errors: true        

    - name: Start all VMs
      virt:
        name: "{{cid}}_t{{ item }}"
        command: start
        state: running
      ignore_errors: true
      become: yes
      with_sequence: "count={{transit_count}}"

    - name: Attach management interface to spine
      command: "virsh attach-interface --domain {{cid}}_t{{ item }} --type network --source {{cid}}mnw_t --model virtio --config --live"
      become: yes
      with_sequence: "count={{transit_count}}"

    - name: Wait for VMs to be started
      pause:
        seconds: 30

    - name: Fetch spine VM IPs
      script: "scripts/getIP.py {{cid}}_t{{ item }}"
      args:
        executable: python
      register: spine_ips
      with_sequence: "count={{transit_count}}"

    - debug:
        msg: "{{item.stdout}}"
      loop: "{{spine_ips.results}}"

    - name: Add Spines to host
      add_host:
        hostname: "{{item.stdout}}"
        ansible_ssh_pass: yashrocks
        groups:
          - hv2_hosts
      loop: "{{spine_ips.results}}"

- name: Ansible create VM playbook
  hosts: [hv1_transits,hv2_transits]
  user: root
  vars_files:
    - vars/setup.yml

  tasks:
    - name: Configure Quagga suite
      script: "scripts/quagga_setup.sh"

    - name: 
#TODODOD
