---
- name: Ansible create VPC
  hosts: [hypervisors]
  user: root
  vars_files:
    - vars/setup.yml
    
  tasks:
    - name: Create spines
      command: "virt-clone --original sampleVM -n {{cid}}_{{vpc}}_s{{ item.id }} --auto-clone"
      become: yes    
      loop: "{{spines}}"

    - name: Attach management interface to spine
      command: "virsh attach-interface --domain {{cid}}_{{vpc}}_s{{ item.id }} --type network --source {{cid}}mnw_s --model virtio --config --live"
      become: yes

    - name: Fetch spine VM IPs
      script: "scripts/get_IP.py {{cid}}_{{vpc}}_s{{ item.id }}"
      args:
        executable: python3

    - name: Add Spines to host
      add_host:




#TODODOD
