---
- name: Connect {{ ns1 }} to {{ ns2 }}
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
    - name: Connecting {{ ns1 }} to {{ ns2 }} via veth
      script: "../scripts/create_veth_ns_ns.sh {{ ns1 }} {{ ns1_ip }} {{ ve_ns1_ns2 }} {{ ns2 }} {{ ns2_ip }}{{ ve_ns2_ns1 }}" 