---
- name: Create docker container playbook
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    default_container_image: centos:7

  tasks:
    # Pull image specified by variable default_image from the Docker Hub
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ c_name }}"
        image: "{{ default_container_image }}"
        state: started
        network_mode: none
        privileged: yes
        memory: "{{ c_ram }}"
        cpuset_cpus: "{{ c_vcpu }}"
        command: sleep infinity
      register: result

      #    - debug:
      # msg: "{{ result.container['State']['Pid'] }}"

    - name: Create symbolic link to network namespace
      file:
        src: "/proc/{{ result.container['State']['Pid'] }}/ns/net"
        dest: "/var/run/netns/{{ c_name }}"
        state: link
