---
- name: Ansible delete client Infra playbook
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  ignore_errors: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: "Delete network {{ nsm }}"
      docker_network:
        name: "{{ nsm }}"
        state: absent
        force: yes
