---
- name: Ansible delete client Infra playbook
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  ignore_errors: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: configure static route
      command: "ip route del {{ nid }} via {{ nsm_h_route }}" 

    - name: Delete veth pair with hypervisor
      shell: "{{ lookup('template', '../scripts/delete_veth_nsm_h.j2') }}"
      args:
        executable: /bin/bash

    - name: Delete network
      script: ../scripts/destroy_net.sh {{ b_net }} {{ b }}

    - name: Delete management namespace
      command: "ip netns del {{ nsm }}"
