---
- name: Ansible delete client Infra playbook
  hosts: [hypervisors]
  user: ece792
  become: yes
  ignore_errors: yes
    
  tasks:
    - name: Delete static route
      command: "ip route del {{ nid }} via {{ nsm_h_ip }}" 

    - name: Delete veth pair with hypervisor
      shell: "../scripts/destroy_veth_hyp.sh {{ ve_h_nsm }}"
      
    - name: Delete network
      script: "../scripts/destory_net.sh {{ b_net }} {{ b }}"

    - name: Delete managment namespace
      command: "ip netns del {{ nsm }}"