---
- name: Ansible delete client Infra playbook
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  ignore_errors: yes
    
  tasks:
    - name: "Delete network {{ nsm }}"
      docker_network:
        name: "{{ nsm }}"
        state: absent
        force: yes
