- name: Install quagga in spine
  hosts: "{{ vm_ip }}"
  user: root
  gather_facts: yes
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - debug:
        msg: "Inside the guest vm"

    - name: Configure Quagga suite
        script: "../scripts/quagga_setup.sh"
