---
- name: Ansible delete customer vm
  hosts: "{{ hypervisor }}"
  user: root
  ignore_errors: yes
  become: yes
    
  tasks:
    - name: Delete a VM 
      script: "../scripts/vm_destroy.sh {{ vm_name }}" 

    - name: Remove image
      command: "rm -f {{ c_vm_image_path }}"
