---
- name: Ansible create customer
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  ignore_errors: yes

  tasks:
    - name: Copy customer VM image
      copy:
        src: "{{ image_path }}"
        dest: "{{ c_vm_image_path }}"
        remote_src: yes
    
    - name: Define a spine VM
      virt:
        name: "{{ vm_name }}"
        command: define
        xml: "{{ lookup('template', '../scripts/create_vm.xml.j2' ) }}"
        uri: 'qemu:///system'

    - name: Start spine VM
      virt:
        name: "{{ vm_name }}"
        command: start
        state: running
      become: yes
    
    - name: Attach management interface to spine
      command: "virsh attach-interface --domain {{ vm_name }} --type network --source {{ mgt_net }} --model virtio --config --live"
      become: yes

    - name: Wait for VMs to be started
      pause:
        seconds: 30
