---
- name: Ansible create customer PC
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  ignore_errors: yes

  tasks:
    - name: Copy client PC image
      copy:
        src: "{{ image_path }}"
        dest: "{{ c_vm_image_path }}"
        remote_src: yes
    
    - name: Define client PC
      virt:
        name: "{{ vm_name }}"
        command: define
        xml: "{{ lookup('template', '../scripts/create_vm.xml.j2' ) }}"
        uri: 'qemu:///system'

    - name: Start client PC
      virt:
        name: "{{ vm_name }}"
        command: start
        state: running
      become: yes
