---
- name: Ansible attach leaf to spine
  hosts: "{{ hypervisor }}"
  user: root
    
  tasks:
    - name: Create network and bridge between l1transit and spine
      script: "../scripts/create_net.sh {{ l1_l2_net }} {{ l1_l2_br }}"
    
    - name: Attach it to spine vm
      command: "virsh attach-interface --domain {{ l1_name }} --type network {{ l1_l2_net }} --model virtio"
    
    - name: Attach it to l1 transit vm
      command: "virsh attach-interface --domain {{ l2_name }} --type network {{ l1_l2_net }} --model virtio"