---
- name: Ansible create spine
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    default_container_image: centos:7
    
  tasks:
    # Pull image specified by variable default_image from the Docker Hub
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ s_name }}"
        image: "{{ default_container_image }}"
        state: started
        privileged: yes
        memory: {{ s_ram }}
        cpuset_cpus: {{ s_vcpu }}
        command: sleep infinity
      register: result

    - name: Create symbolic link to network namespace
      file:
        src: "/proc/{{ result.container['State']['Pid'] }}/ns/net" 
        dest: "/var/run/netns/{{ s_name }}"
        state: link 

    - name: Add spine to management network
      script: "../scripts/create_veth_ns_br_noip.sh {{ s_name }} {{ nsm_br }} {{ ve_s_nsm}} {{ ve_nsm_s}}"

