---
- name: Ansible create spine
  hosts: "{{ hypervisor }}"
  user: root
  ignore_errors: yes
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    # Pull image specified by variable default_image from the Docker Hub
    - name: Create symbolic link to network namespace
      file:
        src: "/proc/{{ result.container['State']['Pid'] }}/ns/net" 
        dest: "/var/run/netns/{{ s_name }}"
        state: unlink
         
    - name: Delete spine container
      docker_container:
        name: "{{ s_name }}"
        state: absent
