---
- name: Ansible BGP multipath
  hosts: "{{ hypervisor }}"
  user: root

  tasks:
    - name: runnning multipatch shell scripts
      script: "../scripts/bgp_multipath.sh {{ self_as }} {{ activate }} {{ c_name }}"
