---
- name: Ansible BGP conf inter transit
  hosts: "{{ hypervisor }}"
  user: root

  tasks:
    - name: Runnning conf inter transit
      script: "../scripts/conf_inter_transit_bgp.sh {{ self_as }} {{ rip1 }} {{ ras1 }} {{ bgp_lo }} {{ c_name }}"
