---
- name: Ansible BGP conf inter transit
  hosts: "{{ hypervisor }}"
  user: root
  become: yes

  tasks:
    - name: Runnning conf inter transit
      script: "../scripts/conf_inter_transit_bgp.sh {{ self_as }} {{ rip }} {{ ras }} {{ bgp_lo }} {{ c_name }}"
