---
- name: Create docker container playbook
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Check if container exists
      shell: "docker ps -a | grep {{pod}}"
      register: c_result

    - name: "Create checkpoint for {{pod}}"
      command: "docker checkpoint create --leave-running=true {{pod}} {{version}}"
      when: "{{pod}} in c_result.stdout"

