---
- name: Ansible create client Infra playbook
  hosts: [localhost]
  user: root
  vars_files:
    - vars/base-config.yml
    - vars/infra-config.yml
    
  tasks:
    - name: install packages
      apt:
        name: "{{ packages }}"
        state: present

    - debug:
        msg: Create VPC here
        
    - name: Create Leaf gateways
      command: "ip netns add {{ base_name }}l{{ item.network_id }}"
      become: yes
      ignore_errors: true
      loop: "{{ subnets }}"

    # Create network and bridge
    - name: Create a network and bridge between namespace and VMs
      script: "scripts/create_net.sh {{base_name}}n{{item.network_id}} {{base_name}}n{{item.network_id}}br"
      loop: "{{ subnets }}"

    # Create veth
    - name: Connect bridge to namespace
      script: "scripts/create_veth_ns_br.sh {{base_name}}l{{item.network_id}} {{ item.ns_ip }} {{base_name}}n{{item.network_id}}br {{base_name}}ve{{item.network_id}}l {{base_name}}ve{{item.network_id}}br"
      loop: "{{ subnets }}"

    # create dnsmasq
    - name: Add route on leaf namespace for veth pair
      command: "ip netns exec {{base_name}}l{{item.network_id}} ip route add {{ item.subnet_base }}/{{ item.subnet_mask }} dev {{base_name}}ve{{item.network_id}}l"
      ignore_errors: true
      become: yes
      loop: "{{ subnets }}"

    - name: Create DHCP server for the leaf gateway
      command: "ip netns exec {{base_name}}l{{item.network_id}} dnsmasq --interface={{base_name}}ve{{item.network_id}}l --dhcp-range={{ item.range }},12h --bind-interfaces --except-interface=lo"
      ignore_errors: true
      become: yes
      loop: "{{ subnets }}"

    # Create VMs
    - name: Clone VMs
      command: "virt-clone --original sampleVM -n {{base_name}}n{{item.0.network_id}}vm{{item.1}} --auto-clone"
      become: yes
      with_subelements: 
        - "{{ subnets }}"
        - vm_ids
    
    - name: Start VMs
      virt:
        name: "{{base_name}}n{{item.0.network_id}}vm{{item.1}}"
        state: running
      become: yes
      with_subelements: 
        - "{{ subnets }}"
        - vm_ids

    - name: Attach interface to VMs
      command: "virsh attach-interface --domain {{base_name}}n{{item.0.network_id}}vm{{item.1}} --type network {{base_name}}n{{item.0.network_id}} --model virtio"
      become: yes
      with_subelements: 
        - "{{ subnets }}"
        - vm_ids
