---
- name: Ansible create client Infra playbook
  hosts: [hypervisors]
  user: root
    
  tasks:
#    - name: install packages
#      apt:
#        name: "{{ packages }}"
#        state: present

    - name: Delete management namespace
      command: "ip netns del {{cid}}_mns"
      become: yes
      ignore_errors: true
    #  namespace:
    #    name: "{{cid}}_mns"
    #    state: present

    - name: Delete network
      script: "scripts/destroy_net.sh {{cid}}mnw_{{item.id}} {{cid}}mbr_{{item.id}}"
      become: yes
      ignore_errors: true
      loop: "{{mgmt_conns}}"

    - name: Delete DHCP server
      shell: "kill -9 $(ps aux | grep 'dnsmasq --interface={{cid}}mve1_{{item.id}} --dhcp-range={{ item.range }},12h --bind-interfaces --except-interface=lo' | head -n 1 | awk '{print $2}')"
      ignore_errors: true
      become: yes
      loop: "{{ mgmt_conns }}"

    # - name: Create veth pair {{network_id}}
    #   command: "ip link add {{cid}}mve1_{{item}} type veth peer name {{cid}}mve2_{{item}}"
    #   become: yes
    #   loop: ['s','t']
    #   ignore_errors: yes

    # - name: Link veth to namespace
    #   command: "ip link set {{cid}}mve1_{{item}} netns {{cid}}_mns"
    #   become: yes
    #   loop: ['s','t']
    #   ignore_errors: yes

    # - name: Link veth to bridge
    #   command: "brctl addif {{cid}}mbr_{{item}} {{cid}}mve1_{{item}}"
    #   become: yes
    #   loop: ['s','t']
    #
    #   ignore_errors: yes
