---
- name: Ansible attach leaf to spine
  hosts: "{{ hypervisor }}"
  user: root
    
  tasks:
    - name: "Create network {{ nsm }}"
      docker_network:
        name: "{{ nsm }}"
        ipam_config:
          - subnet: "{{ nsm_subnet }}"

    - name: Add containers to a network
      docker_network:
        name: "{{ l_name }}_{{ s_name }}"
        connected:
          - "{{ l_name }}"
          - "{{ s_name }}"
        appends: yes
        