---
- name: Ansible create VM playbook
  hosts: [localhost]
  user: root

  tasks:
# VM configuration: creating, starting and attaching interfaces
    - name: Copy sample image
      copy:
        src: "{{ sample_image | default('/var/lib/libvirt/images/sampleBuild.img')}}"
        dest: "/var/lib/libvirt/images/{{ item.name }}.img"
        remote_src: yes
      loop: "{{ VMs }}"

    - name: Define a VM
      virt:
        name: "{{ item.name }}"
        command: define
        xml: "{{ lookup('template', 'vm_template/sampleVM.xml.j2' ) }}"
        uri: 'qemu:///system'
      loop: "{{ VMs }}"

    - name: Start all VMs
      virt:
        name: "{{ item.name }}"
        command: start
        state: running
      ignore_errors: true
      loop: "{{ VMs }}"

    - name: Attach interface to VM1
      command: "virsh attach-interface --domain {{ item.0.name }} --type network --source {{ item.1 }} --model virtio --config --live"
      become: yes
      with_subelements: 
        - "{{ VMs }}"
        - networks
