---
- name: Ansible configure outer tranist
  hosts: "{{ vm_ip }}"
  user: root
  become: yes
    
  tasks:
    - name: Configure Quagga suite
      script: "../scripts/quagga_setup.sh"

    - name: Configure loopback address
      command: "ip addr add {{ t_loopback_ip }} dev lo"
