---
- name: Ansible attach leaf to spine
  hosts: "{{ outer_transit }}"
  user: root
    
  tasks:
    - name: GRE config on loca hosts
      script: "../scripts/gre_tunnel.sh add {{ o_t_ip }} {{ r_i_t_ip }} {{ r_vm_subnet }}"