---
- name: Ansible attach remote transit VM
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
    
  tasks:
    - name: Adding GRE tunnel to {{ t_name }}
      command: "ip netns exec {{ t_name }} ip tunnel add {{ gre_tunnel_name }} mode gre local {{ local_transit_ip }} remote {{ remote_transit_ip }}"

    - name: Bring GRE interface up on  {{ t_name }}
      command: "ip netns exec {{ t_name }} ip link set dev {{ gre_tunnel_name }} up"    

    - name: Adding remote subnet to {{ t_name }}
      command: "ip netns exec {{ t_name }} ip route add {{ remote_subnet }} dev {{ gre_tunnel_name }}"    
