---
- name: Ansible create spine
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  ignore_errors: yes

  tasks:
    - name: Copy Transit VM image
      copy:
        src: "{{ image_path }}"
        dest: "{{ c_t_image_path }}"
        remote_src: yes
    
    - name: Define a transit VM
      virt:
        name: "{{ t_name }}"
        command: define
        xml: "{{ lookup('template', '../scripts/create_transit.xml.j2' ) }}"
        uri: 'qemu:///system'

    - name: Start transit VM
      virt:
        name: "{{ t_name }}"
        command: start
        state: running
      become: yes
    
    - name: Attach management interface to transit
      command: "virsh attach-interface --domain {{ t_name }} --type network --source {{ mgt_net }} --model virtio --config --live"
      become: yes

    - name: Wait for VMs to be started
      pause:
        seconds: 30
