---
- name: Ansible create transit
  hosts: "{{ hypervisor }}"
  user: root
  become: yes
  ignore_errors: yes

  tasks:
    - name: Copy transit VM image
      copy:
        src: "{{ image_path }}"
        dest: "{{ c_t_image_path }}"
        remote_src: yes
    
    - name: Define a transit VM
      virt:
        name: "{{ t_name }}"
        command: define
        xml: "{{ lookup('template', '../scripts/create_transit.xml.j2' ) }}"
        uri: 'qemu:///system'

    - name: Start transit VM
      virt:
        name: "{{ t_name }}"
        command: start
        state: running
      become: yes
    
    - name: Attach management interface to trasit
      command: "virsh attach-interface --domain {{ t_name }} --type network --source {{ mgt_net }} --model virtio --config --live"
      become: yes

    - name: Create network between trasnit and hypervisor
      script: "../scripts/create_net.sh {{ t_h_net }} {{ t_h_br }}"
      become: yes

    - name: Assign IP to bridge network between lead and spine
      command: "ip addr add {{ b_ip }} dev {{ t_h_br }}"

    - name: Create DHCP server to connect leaf to spine
      command: "dnsmasq --interface={{ t_h_br }} --dhcp-range={{ dhcp_range }},infinite --bind-interfaces --except-interface=lo"

    - name: Attach hypervisor interface to transit
      command: "virsh attach-interface --domain {{ t_name }} --type network --source {{ t_h_net }} --model virtio --config --live"
      become: yes


    - name: Wait for VMs to be started
      pause:
        seconds: 30
